version: '3'
services:
  mysql-aws:
    build:
      context: .
    image: chatwork/mysql-aws
  sut:
    image: chatwork/dgoss:latest
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    entrypoint: ""
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/mysql-aws tail -f /dev/null
    container_name: mysql-aws
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - mysql-aws
