version: '3'
services:
  actions-runner-controller-helmfile:
    build:
      context: .
    image: chatwork/actions-runner-controller-helmfile:latest
  sut:
    image: chatwork/dgoss:latest
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    entrypoint: ""
    command: /usr/local/bin/dgoss run --entrypoint tail chatwork/actions-runner-controller-helmfile -f /dev/null
    container_name: actions-runner-controller-helmfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - actions-runner-controller-helmfile
