FROM chatwork/alpine-sdk:3.15

ARG GOMPLATE_VERSION=3.11.0

LABEL version="v${GOMPLATE_VERSION}"
LABEL maintainer="sakamoto@chatwork.com"

ADD https://github.com/hairyhenderson/gomplate/releases/download/v${GOMPLATE_VERSION}/gomplate_linux-arm64 /usr/local/bin/gomplate

RUN chmod 0755 /usr/local/bin/gomplate

ENTRYPOINT ["/usr/local/bin/gomplate"]
CMD ["-h"]
