version: '3'
services:
  gomplate:
    build:
      context: .
    image: chatwork/gomplate
  sut:
    image: chatwork/dgoss:latest
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    entrypoint: ""
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/gomplate tail -f /dev/null
    container_name: gomplate
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gomplate
