version: '3'
services:
  argocd-helmfile-plugin:
    build:
      context: .
    image: chatwork/argocd-helmfile-plugin
  sut:
    image: chatwork/dgoss:latest
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    entrypoint: ""
    command: /usr/local/bin/dgoss run --entrypoint tail chatwork/argocd-helmfile-plugin -f /dev/null
    container_name: argocd-helmfile-plugin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - argocd-helmfile-plugin
