version: '3'
services:
  yq:
    build:
      context: .
    image: chatwork/yq
  sut:
    image: chatwork/dgoss:latest
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    entrypoint: ""
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/yq tail -f /dev/null
    container_name: yq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - yq
