FROM adoptopenjdk/openjdk8:x86_64-alpine-jdk8u181-b13

LABEL version="x86_64-alpine-jdk8u181-b13"
LABEL maintainer="Tomoyoshi Ogura <ogura@chatwork.com>"

ADD ./cacerts /opt/java/openjdk/jre/lib/security/cacerts
