version: '3'
services:
  chatwork-notify:
    build:
      context: .
    image: chatwork/chatwork-notify
  sut:
    image: chatwork/dgoss:latest
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    entrypoint: ""
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/chatwork-notify tail -f /dev/null
    container_name: chatwork-notify
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - chatwork-notify
