version: '3'
services:
  conftest:
    build:
      context: .
    image: chatwork/conftest
  sut:
    image: chatwork/dgoss:latest
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    entrypoint: ""
    command: /usr/local/bin/dgoss run --entrypoint tail chatwork/conftest -f /dev/null
    container_name: conftest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - conftest
