version: '3'
services:
  openapi2jsonschema:
    build:
      context: .
    image: chatwork/openapi2jsonschema
  sut:
    image: chatwork/dgoss:latest
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    entrypoint: ""
    command: /usr/local/bin/dgoss run --entrypoint tail chatwork/openapi2jsonschema -f /dev/null
    container_name: openapi2jsonschema
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - openapi2jsonschema
