version: '3'
services:
  postfix:
    build:
      context: .
    image: chatwork/postfix
  sut:
    image: chatwork/dgoss:latest
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
      GOSS_SLEEP: 5
    command: /usr/local/bin/dgoss run chatwork/postfix
    entrypoint: ""
    container_name: postfix
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postfix
  sut-with-sasl_passwd:
    image: chatwork/dgoss:latest
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
      GOSS_SLEEP: 5
    entrypoint: ""
    command: /bin/bash /goss/test_command.sh
    container_name: postfix-with-sasl_passwd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postfix
