FROM amazon/aws-cli:latest

ARG AWSCLI_VERSION=2.4.14

LABEL version="${AWSCLI_VERSION}"
LABEL maintainer="ozaki@chatwork.com"
LABEL maintainer="sakamoto@chatwork.com"

COPY entrypoint.sh /entrypoint.sh

RUN yum install jq -y \
    && yum clean all \
    && rm -rf /var/cache/yum/* \
    && chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
