version: '3'
services:
  provider_terraform_controller:
    build:
      context: .
    image: chatwork/provider-terraform-controller
  sut:
    image: chatwork/dgoss:latest
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    entrypoint: ""
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/provider-terraform-controller tail -f /dev/null
    container_name: provider-terraform-controller
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - provider_terraform_controller
