version: '3'
services:
  alpine-sdk:
    build:
      context: .
    image: chatwork/alpine-sdk
  sut:
    image: chatwork/dgoss:latest
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    entrypoint: ""
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/alpine-sdk tail -f /dev/null
    container_name: alpine-sdk
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - alpine-sdk
