version: '3'
services:
  envsubst:
    build:
      context: .
    image: chatwork/envsubst
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/envsubst tail -f /dev/null
    container_name: envsubst
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - envsubst
