version: '3'
services:
  circleci-docker:
    build:
      context: .
    image: chatwork/circleci-docker
  sut:
    image: chatwork/dgoss:latest
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    entrypoint: ""
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/circleci-docker:latest tail -f /dev/null
    container_name: circleci-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - circleci-docker
