file:
  /usr/local/bin/helmfile:
    exists: true
    mode: "0755"
  /usr/local/bin/helm:
    exists: true
    mode: "0755"
  /usr/local/bin/kubectl:
    exists: true
    mode: "0755"
  /usr/bin/aws:
    exists: true
    mode: "0755"
command:
  /usr/local/bin/helmfile -v:
    exit-status: 0
  /usr/local/bin/helm version:
    exit-status: 0
  /usr/local/bin/helm plugin list:
    exit-status: 0
    stdout:
      - /^diff/
      - /^helm-git/
      - /^secrets/
      - /^x/
  /usr/local/bin/kubectl version --client:
    exit-status: 0
  /usr/bin/aws --version:
    exit-status: 0
