version: '3'
services:
  flyway-mysql56:
    build:
      context: .
    image: chatwork/flyway-mysql56
    entrypoint: /bin/bash
  sut:
    image: chatwork/dgoss:latest
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    entrypoint: ""
    command: /usr/local/bin/dgoss run --entrypoint "" chatwork/flyway-mysql56 tail -f /dev/null
    container_name: flyway-mysql56
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - flyway-mysql56
