version: '3'
services:
  dgoss:
    build:
      context: .
    image: chatwork/dgoss
    entrypoint: /bin/bash
  sut:
    image: chatwork/dgoss:latest
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    entrypoint: ""
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/dgoss tail -f /dev/null
    container_name: dgoss
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - dgoss
