version: '3'
services:
  dgoss:
    build:
      context: .
    image: chatwork/dgoss
    entrypoint: /bin/bash
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run --entrypoint '' chatwork/dgoss:dev tail -f /dev/null
    container_name: dgoss
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - dgoss
