version: '3'
services:
  newrelic-php-agent:
    build:
      context: .
    image: chatwork/newrelic-php-agent
  sut:
    image: chatwork/dgoss:latest
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    entrypoint: ""
    command: /usr/local/bin/dgoss run --entrypoint tail chatwork/newrelic-php-agent -f /dev/null
    container_name: newrelic-php-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - newrelic-php-agent
