command:
  /usr/local/bin/sops -v:
    exit-status: 0
  /usr/local/bin/argocd version:
    exit-status: 1
    stdout:
    - "3.0.11"
  /usr/local/bin/kubectl version --client:
    exit-status: 0
  /usr/local/bin/helm plugin list:
    exit-status: 0
    stdout:
      - /^diff/
      - /^helm-git/
      - /^secrets/
  /usr/local/bin/helm version:
    exit-status: 0
    stdout:
      - "3.18.4"
  /usr/local/bin/helmfile -v:
    exit-status: 0
    stdout:
      - "1.1.3"
