command:
  /usr/local/bin/sops -v:
    exit-status: 0
  /usr/local/bin/argocd version:
    exit-status: 1
    stdout:
    - 2.11.3
  /usr/local/bin/kubectl version --client:
    exit-status: 0
  /usr/local/bin/helm plugin list:
    exit-status: 0
    stdout:
      - /^diff/
      - /^helm-git/
      - /^secrets/
  /usr/local/bin/helm version:
    exit-status: 0
    stdout:
      - 3.15.1
  /usr/local/bin/helmfile -v:
    exit-status: 0
    stdout:
      - 0.165.0
