command:
  /usr/local/bin/argocd version:
    exit-status: 1
    stdout:
    - 2.3.2
  /usr/local/bin/kubectl version:
    exit-status: 1
    stdout:
    - 1.21.11
  /usr/local/bin/helm plugin list:
    exit-status: 0
    stdout:
      - /^diff/
      - /^helm-git/
      - /^secrets/
      - /^x/
  /usr/local/bin/helm version:
    exit-status: 0
    stdout:
      - 3.8.1
  /usr/local/bin/helmfile -v:
    exit-status: 0
    stdout:
      - 0.143.5
