command:
  /usr/local/bin/argocd version:
    exit-status: 1
    stdout:
    - 2.1.3
  /usr/local/bin/kubectl version:
    exit-status: 1
    stdout:
    - 1.20.7
  /usr/local/bin/helm plugin list:
    exit-status: 0
    stdout:
      - /^diff/
      - /^helm-git/
      - /^secrets/
      - /^s3/
      - /^x/
  /usr/local/bin/helm version:
    exit-status: 0
    stdout:
      - 3.7.1
  /usr/local/bin/helmfile -v:
    exit-status: 0
    stdout:
      - 0.141.0
