version: '3'
services:
  flyway:
    build:
      context: .
    image: chatwork/flyway
    entrypoint: /bin/bash
  sut:
    image: chatwork/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
      GOSS_WAIT_OPTS: -r 10s --sleep 1s
    entrypoint: ""
    command: /usr/local/bin/dgoss run chatwork/flyway-mysql57 tail -f /dev/null
    container_name: flyway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./goss/goss.yaml:/goss/goss.yaml
    depends_on:
      - flyway
